name: webview_cookie_manager
description: A new flutter plugin project.
version: 1.0.0+1
repository: https://github.com/amag2511/webview_cookie_manager

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.webview_cookie_manager
        pluginClass: WebviewCookieManagerPlugin
      ios:
        pluginClass: WebviewCookieManagerPlugin
